Morphology:
  structure: structure.cml
  parameters: structure.spf
Analysis:
  Dipole:
    enabled: false
    label: unset
    qp_charge_file: null
    vol_per_mol: null
    do_select: false
    select_z_cutoff: null
    select_mol_type: null
    plot_heatmaps: false
  GSP:
    enabled: false
    cutoff: 1.0
    outfile_basename: GSP_analysis_system
    do_select: false
    select_mol_type: null
    select_z_cutoff: null
    do_ewald: false
    box_size: 10.0
    rename_atoms: false
    qp_charge_file: null
  QPGSP:
    enabled: false
    homo_lumo_file: molid_homo_lumo_total.dat
  Orientation:
    axis:
      enabled: false
      '0':
        Ids: [0, 1]
        moltype: null
        label: unset
      bins: 15
    complex_axis:
      enabled: false
      '0':
        atom:
          '0':
            id: 0
            multiplier: -1
          '1':
            id: 1
            multiplier: 1
        moltype: null
        label: unset
    normal:
      enabled: false
      relative: false
      neighbor_relative: false
      core_ids: [0]
      '0':
        Ids: [2, 5, 7]
        moltype: null
        label: unset
      bins: 15
    plot_heatmaps: false
  Density:
    enabled: true
    inner_box_cutoff: 10.0
    no_samples: 20
  RDF:
    enabled: true
    cutoff: 20
  AtomicDistance:
    enabled: false
    atomIds: [0]
    numberMolecules: 1
