#!/bin/bash
#SBATCH --nodes=10
#SBATCH --tasks-per-node=76
#SBATCH -t 0-72:00:00
#SBATCH -e stderr
#SBATCH -o stdout
#SBATCH --mail-type=FAIL,END
#SBATCH -J CBP@CN6-CP_0.2
#SBATCH --mail-user=artem.fediai@nanomatch.com
#SBATCH --partition cpuonly
#SBATCH -A hk-project-doled


#QP=/hkfs/home/project/hk-project-zimnano/nz8308/nanomatch-control-repo/src/qp_dev/quantumpatch/QuantumPatch/QuantumPatchNG.py


# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/hkfs/home/project/hk-project-zimnano/nz8308/.local/bin/micromamba';
export MAMBA_ROOT_PREFIX='/hkfs/home/project/hk-project-zimnano/nz8308/micromamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<


micromamba activate vc_syncfix
export OMP_NUM_THREADS=1

cd $SLURM_SUBMIT_DIR


mpirun --bind-to none $NMMPIARGS $ENVCOMMAND --hostfile $HOSTFILE  python -m mpi4py `which QuantumPatch` >> progress.txt 2> shredder_mpi_stderr
